### ISSUE TITLE
Como fisioterapeuta, gostaria de logar no sistema

### ISSUE THREAD

**Issue by barbgluz** [fisufba/fisufba#1]
Related issues:

 - [ ] fisufba/fisufba-client#1
 - [ ] fisufba/fisufba-client#2
 - [ ] fisufba/fisufba-server#1
 - [ ] fisufba/fisufba-server#2
