### ISSUE TITLE
Como atendimento gostaria de preencher o formulário de avaliação cinético-funcional de um paciente

### ISSUE THREAD

**Issue by thelink2012** [fisufba/fisufba#15]
Related issues:

+ [ ] fisufba/fisufba-client#3
+ [ ] fisufba/fisufba-client#4
+ [ ] fisufba/fisufba-client#5
+ [ ] fisufba/fisufba-client#6
+ [ ] fisufba/fisufba-server#3
+ [ ] fisufba/fisufba-server#4
+ [ ] fisufba/fisufba-server#5
+ [ ] fisufba/fisufba-server#6
